import type {Metadata} from 'next';
import {NavBar} from './_components/NavBar';
import {Inter} from 'next/font/google';
import './globals.css';
import Layout from './_components/FreezeRouter';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
